#ifndef NEOC_PROTOCOL_RESPONSE_EXPRESS_CONTRACT_STATE_H
#define NEOC_PROTOCOL_RESPONSE_EXPRESS_CONTRACT_STATE_H

#include "neoc/protocol/core/response/express_contract_state.h"

#endif /* NEOC_PROTOCOL_RESPONSE_EXPRESS_CONTRACT_STATE_H */
