#ifndef NEOC_PROTOCOL_RESPONSE_TRANSACTION_ATTRIBUTE_H
#define NEOC_PROTOCOL_RESPONSE_TRANSACTION_ATTRIBUTE_H

#include "neoc/protocol/core/response/transaction_attribute.h"

#endif /* NEOC_PROTOCOL_RESPONSE_TRANSACTION_ATTRIBUTE_H */
